version: "2"
checks:
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - .*
  - build/
  - node_modules/
  - dist/
  - tasks/
  - test/
  - app/bin
  - app/img/
  - app/testdata/
  - app/src/frontend/vue/substores/
  - app/src/frontend/spec/
