language: node_js
node_js:
  - "node"
before_install:
  - cp config-example.json config.json
before_script:    
  - npm run www-no-watch
addons:
  chrome: stable
cache:
  directories:
    - "node_modules"
